# Generated by Django 3.1.7 on 2021-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=25)),
                ('date', models.DateField()),
                ('quantite_recu', models.FloatField()),
                ('service', models.CharField(choices=[('Pédiatrie', 'Pédiatrie'), ('Maternité', 'Maternité'), ('Médecine interne', 'Médecine interne'), ('Bloc Opératoire', 'Bloc Opératoire'), ('Néonatologie', 'Néonatologie'), ('Autres services', 'Autres services'), ('Quantité détruite', 'Quantité détruite')], max_length=50)),
                ('quantite_restant', models.FloatField()),
                ('quantite_demandee', models.FloatField()),
                ('quantite_servi', models.FloatField()),
                ('observations', models.TextField()),
            ],
        ),
    ]
